/**
 * SpongeblogSP API
 * Spongeblog blogging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BlogUserDetails {
    /**
     * Login name of the user.
     */
    userName?: string;

    authorities?: Array<models.BlogAuthority>;

}
